research_task:
  description: >
    Conduct a thorough research about Haiti across the websites provided.
    
    - Le Nouvelliste (https://lenouvelliste.com/) & make sure research is done by the Le Nouvelliste reporter.
    - Loop News Haiti (https://haiti.loopnews.com/) & make sure research is done by the Loop News Haiti reporter.
    - The Haitian Times (https://haitiantimes.com/) & make sure research is done by the Haitian Times reporter.
    - Ayibopost (https://ayibopost.com/) & make sure research is done by the Ayibopost reporter.
    - Radio France Internationale (https://www.rfi.fr/en/tag/haiti/) & make sure research is done by the Radio France Internationale reporter.
    - New York Times (https://www.nytimes.com/topic/destination/haiti) & make sure research is done by the New York Times reporter.
    - CNN (https://www.cnn.com/search?q=Haiti&from=0&size=10&page=1&sort=newest&types=all&section=) & make sure research is done by the CNN reporter.

    Make sure you find any interesting and relevant information given the current date is 10-10-2024.
  expected_output: >
    A list with 5 bullet points representing solution-oriented questions to pose to social media for how to fix any problems being
    addressed by Haiti. Include detailed sources and citations for each bulletpoint in your report so that the information can be verified.
    Include links to the sources in the final output.
